#alloc <full-comp=0, read-alloc=1, write-alloc=2>
#repl <lru=0, fifo=1>
#evict <write-back=0, write-through=1>

arch: 0
assoc: 8
policy: 
  - alloc: 0
  - repl: 0
  - evict: 1
bitwidth: 128
energy_model:
  - rfc.r: 43.2275
  - rfc.w: 44.0041
  - mrf.r: 17.4632 
  - mrf.w: 17.9704
