arch: 0
assoc: 2
n_block: 8
n_dw: 1
window_len: 0
policy: 
  - alloc: 2
  - repl: 1
  - evict: 0
  - dest_map: 1
bitwidth: 128
energy_model:
  - rfc.r: 23.4685
  - rfc.w: 24.2801
  - mrf.r: 17.4632 
  - mrf.w: 17.9704

