#alloc <full-comp=0, read-alloc=1, write-alloc=2>
#repl <lru=0, fifo=1>
#evict <write-back=0, write-through=1>

arch: 0
assoc: 2
policy: 
  - alloc: 3
  - repl: 0
  - evict: 0
bitwidth: 32
energy_model:
  - rfc.r: 7.31519
  - rfc.w: 8.76570
  - mrf.r: 17.4632 
  - mrf.w: 17.9704

