arch: 0
assoc: 4
n_block: 8
n_dw: 1
policy: 
  - alloc: 2
  - repl: 1
  - evict: 0
  - dest_map: 0
bitwidth: 128
energy_model:
  - rfc.r: 35.3369
  - rfc.w: 36.701
  - mrf.r: 17.4632 
  - mrf.w: 17.9704

