#alloc <full-comp=0, read-alloc=1, write-alloc=2>
#repl <lru=0, fifo=1>
#evict <write-back=0, write-through=1>

arch: 0
assoc: 2
policy: 
  - alloc: 0
  - repl: 0
  - evict: 1
energy_model:
  - rfc.r: 5.4969
  - rfc.w: 6.44151
  - mrf.r: 45.4802
  - mrf.w: 47.2171

