#pragma once

#include <unordered_map>
#include <stdexcept>
#include <iostream>

namespace op {

	enum Opcode {
		// artificial op
		OP_VOID = 0,
		
		// Basic (Volta) SASS op
		OP_FADD = 1,
  		OP_FADD32I,
  		OP_FCHK,
  		OP_FFMA32I,
  		OP_FFMA,
  		OP_FMNMX,
  		OP_FMUL,
  		OP_FMUL32I,
  		OP_FSEL,
  		OP_FSET,
  		OP_FSETP,
  		OP_FSWZADD,
  		OP_MUFU,
  		OP_HADD2,
  		OP_HADD2_32I,
  		OP_HFMA2,
  		OP_HFMA2_32I,
  		OP_HMUL2,
  		OP_HMUL2_32I,
  		OP_HSET2,
  		OP_HSETP2,
  		OP_HMMA,
  		OP_DADD,
  		OP_DFMA,
  		OP_DMUL,
  		OP_DSETP,
  		OP_BMSK,
  		OP_BREV,
  		OP_FLO,
  		OP_IABS,
  		OP_IADD,
  		OP_IADD3,
  		OP_IADD32I,
  		OP_IDP,
		OP_IDP4A,
		OP_IMAD,	
		OP_IMMA,
		OP_IMNMX,
		OP_IMUL,
		OP_IMUL32I,	
		OP_ISCADD,
  		OP_ISCADD32I,
  		OP_ISETP,
  		OP_LEA,
  		OP_LOP,
  		OP_LOP3,
  		OP_LOP32I,
  		OP_POPC,
  		OP_SHF,
  		OP_SHR,
  		OP_VABSDIFF,
  		OP_VABSDIFF4,
  		OP_VADD,
  		OP_F2F,
  		OP_F2I,
  		OP_I2F,
  		OP_I2I,
  		OP_I2IP,
  		OP_FRND,
  		OP_MOV,
  		OP_MOV32I,
  		OP_PRMT,
  		OP_SEL,
  		OP_SGXT,
  		OP_SHFL,
  		OP_PLOP3,
  		OP_PSETP,
  		OP_P2R,
  		OP_R2P,
  		OP_LD,
  		OP_LDC,
  		OP_LDG,
  		OP_LDL,
  		OP_LDS,
  		OP_ST,
  		OP_STG,
  		OP_STL,
  		OP_STS,
  		OP_MATCH,
  		OP_QSPC,
  		OP_ATOM,
  		OP_ATOMS,
  		OP_ATOMG,
  		OP_RED,
  		OP_CCTL,
  		OP_CCTLL,
  		OpcodeRRBAR,
  		OP_MEMBAR,
  		OP_CCTLT,
  		OP_TEX,
  		OP_TLD,
  		OP_TLD4,
  		OP_TMML,
  		OP_TXD,
  		OP_TXQ,
  		OP_BMOV,
  		OP_BPT,
  		OP_BRA,
  		OP_BREAK,
  		OP_BRX,
  		OP_BSSY,
  		OP_BSYNC,
  		OP_CALL,
  		OpcodeXIT,
  		OP_JMP,
  		OP_JMX,
  		OP_KILL,
  		OP_NANOSLEEP,
  		OP_RET,
  		OP_RPCMOV,
  		OP_RTT,
  		OP_WARPSYNC,
  		OP_YIELD,
  		OP_B2R,
  		OP_BAR,
  		OP_CS2R,
  		OP_CSMTEST,
  		OP_DEPBAR,
  		OP_GETLMEMBASE,
  		OP_LEPC,
  		OP_NOP,
  		OP_PMTRIG,
  		OP_R2B,
  		OP_S2R,
  		OP_SETCTAID,
  		OP_SETLMEMBASE,
  		OP_VOTE,
  		OP_VOTE_VTG,

		// Unique ops for Turing SASS		
  		OP_BMMA,
  		OP_MOVM,
  		OP_LDSM,
  		OP_R2UR,
  		OP_S2UR,
  		OP_UBMSK,
  		OP_UBREV,
  		OP_UCLEA,
  		OP_UFLO,
  		OP_UIADD3,
  		OP_UIMAD,
  		OP_UISETP,
  		OP_ULDC,
  		OP_ULEA,
  		OP_ULOP,
  		OP_ULOP3,
  		OP_ULOP32I,
  		OP_UMOV,
  		OP_UP2UR,
  		OP_UPLOP3,
  		OP_UPOPC,
  		OP_UPRMT,
  		OP_UPSETP,
  		OP_UR2UP,
  		OP_USEL,
  		OP_USGXT,
  		OP_USHF,
  		OP_USHL,
  		OP_USHR,
  		OP_VOTEU,
  		OP_SUATOM,
  		OP_SULD,
  		OP_SURED,
  		OP_SUST,
  		OP_BRXU,
  		OP_JMXU,

		// Total number of ops
		SASS_NUM_opS
	};

	// Opcode -> std::string
    const std::unordered_map<Opcode, std::string> op2str_tab {
    	std::pair<Opcode, std::string>(OP_VOID, "VOID"),
    	std::pair<Opcode, std::string>(OP_FADD, "FADD"),
  		std::pair<Opcode, std::string>(OP_FADD32I, "FADD32I"),
  		std::pair<Opcode, std::string>(OP_FCHK, "FCHK"),
  		std::pair<Opcode, std::string>(OP_FFMA32I, "FFMA32I"),
  		std::pair<Opcode, std::string>(OP_FFMA, "FFMA"),
  		std::pair<Opcode, std::string>(OP_FMNMX, "FMNMX"),
  		std::pair<Opcode, std::string>(OP_FMUL, "FMUL"),
  		std::pair<Opcode, std::string>(OP_FMUL32I, "FMUL32I"),
  		std::pair<Opcode, std::string>(OP_FSEL, "FSEL"),
  		std::pair<Opcode, std::string>(OP_FSET, "FSET"),
  		std::pair<Opcode, std::string>(OP_FSETP, "FSETP"),
  		std::pair<Opcode, std::string>(OP_FSWZADD, "FSWZADD"),
  		std::pair<Opcode, std::string>(OP_MUFU, "MUFU"),
  		std::pair<Opcode, std::string>(OP_HADD2, "HADD2"),
  		std::pair<Opcode, std::string>(OP_HADD2_32I, "HADD2_32I"),
  		std::pair<Opcode, std::string>(OP_HFMA2, "HFMA2"),
  		std::pair<Opcode, std::string>(OP_HFMA2_32I, "HFMA2_32I"),
  		std::pair<Opcode, std::string>(OP_HMUL2, "HMUL2"),
  		std::pair<Opcode, std::string>(OP_HMUL2_32I, "HMUL2_32I"),
  		std::pair<Opcode, std::string>(OP_HSET2, "HSET2"),
  		std::pair<Opcode, std::string>(OP_HSETP2, "HSETP2"),
  		std::pair<Opcode, std::string>(OP_HMMA, "HMMA"),
  		std::pair<Opcode, std::string>(OP_DADD, "DADD"),
  		std::pair<Opcode, std::string>(OP_DFMA, "DFMA"),
  		std::pair<Opcode, std::string>(OP_DMUL, "DMUL"),
  		std::pair<Opcode, std::string>(OP_DSETP, "DSETP"),
  		std::pair<Opcode, std::string>(OP_BMSK, "BMSK"),
  		std::pair<Opcode, std::string>(OP_BREV, "BREV"),
  		std::pair<Opcode, std::string>(OP_FLO, "FLO"),
  		std::pair<Opcode, std::string>(OP_IABS, "IABS"),
  		std::pair<Opcode, std::string>(OP_IADD, "IADD"),
  		std::pair<Opcode, std::string>(OP_IADD3, "IADD3"),
  		std::pair<Opcode, std::string>(OP_IADD32I, "IADD32I"),
  		std::pair<Opcode, std::string>(OP_IDP, "IDP"),
		std::pair<Opcode, std::string>(OP_IDP4A, "IDP4A"),
		std::pair<Opcode, std::string>(OP_IMAD, "IMAD"),	
		std::pair<Opcode, std::string>(OP_IMMA, "IMMA"),
		std::pair<Opcode, std::string>(OP_IMNMX, "IMNMX"),
		std::pair<Opcode, std::string>(OP_IMUL, "IMUL"),
		std::pair<Opcode, std::string>(OP_IMUL32I,	"IMUL32I"),
		std::pair<Opcode, std::string>(OP_ISCADD, "ISCADD"),
  		std::pair<Opcode, std::string>(OP_ISCADD32I, "ISCADD32I"),
  		std::pair<Opcode, std::string>(OP_ISETP, "ISETP"),
  		std::pair<Opcode, std::string>(OP_LEA, "LEA"),
  		std::pair<Opcode, std::string>(OP_LOP, "LOP"),
    	std::pair<Opcode, std::string>(OP_LOP3, "LOP3"),
  		std::pair<Opcode, std::string>(OP_LOP32I, "LOP32I"),
  		std::pair<Opcode, std::string>(OP_POPC, "POPC"),
  		std::pair<Opcode, std::string>(OP_SHF, "SHF"),
  		std::pair<Opcode, std::string>(OP_SHR, "SHR"),
  		std::pair<Opcode, std::string>(OP_VABSDIFF, "VABSDIFF"),
  		std::pair<Opcode, std::string>(OP_VABSDIFF4, "VABSDIFF4"),
  		std::pair<Opcode, std::string>(OP_VADD, "VADD"),
  		std::pair<Opcode, std::string>(OP_F2F, "F2F"),
  		std::pair<Opcode, std::string>(OP_F2I, "F2I"),
  		std::pair<Opcode, std::string>(OP_I2F, "I2F"),
  		std::pair<Opcode, std::string>(OP_I2I, "I2I"),
  		std::pair<Opcode, std::string>(OP_I2IP, "I2IP"),
  		std::pair<Opcode, std::string>(OP_FRND, "FRND"),
  		std::pair<Opcode, std::string>(OP_MOV, "MOV"),
  		std::pair<Opcode, std::string>(OP_MOV32I, "MOV32I"),
  		std::pair<Opcode, std::string>(OP_PRMT, "PRMT"),
  		std::pair<Opcode, std::string>(OP_SEL, "SEL"),
  		std::pair<Opcode, std::string>(OP_SGXT, "SGXT"),
  		std::pair<Opcode, std::string>(OP_SHFL, "SHFL"),
  		std::pair<Opcode, std::string>(OP_PLOP3, "PLOP3"),
  		std::pair<Opcode, std::string>(OP_PSETP, "PSETP"),
  		std::pair<Opcode, std::string>(OP_P2R, "P2R"),
  		std::pair<Opcode, std::string>(OP_R2P, "R2P"),
  		std::pair<Opcode, std::string>(OP_LD, "LD"),
  		std::pair<Opcode, std::string>(OP_LDC, "LDC"),
  		std::pair<Opcode, std::string>(OP_LDG, "LDG"),
  		std::pair<Opcode, std::string>(OP_LDL, "LDL"),
  		std::pair<Opcode, std::string>(OP_LDS, "LDS"),
  		std::pair<Opcode, std::string>(OP_ST, "ST"),
  		std::pair<Opcode, std::string>(OP_STG, "STG"),
  		std::pair<Opcode, std::string>(OP_STL, "STL"),
  		std::pair<Opcode, std::string>(OP_STS, "STS"),
  		std::pair<Opcode, std::string>(OP_MATCH, "MATCH"),
  		std::pair<Opcode, std::string>(OP_QSPC, "QSPC"),
  		std::pair<Opcode, std::string>(OP_ATOM, "ATOM"),
  		std::pair<Opcode, std::string>(OP_ATOMS, "ATOMS"),
  		std::pair<Opcode, std::string>(OP_ATOMG, "ATOMG"),
  		std::pair<Opcode, std::string>(OP_RED, "RED"),
  		std::pair<Opcode, std::string>(OP_CCTL, "CCTL"),
  		std::pair<Opcode, std::string>(OP_CCTLL, "CCTLL"),
  		std::pair<Opcode, std::string>(OpcodeRRBAR, "ERRBAR"),
  		std::pair<Opcode, std::string>(OP_MEMBAR, "MEMBAR"),
  		std::pair<Opcode, std::string>(OP_CCTLT, "CCTLT"),
  		std::pair<Opcode, std::string>(OP_TEX, "TEX"),
  		std::pair<Opcode, std::string>(OP_TLD, "TLD"),
  		std::pair<Opcode, std::string>(OP_TLD4, "TLD4"),
  		std::pair<Opcode, std::string>(OP_TMML, "TMML"),
  		std::pair<Opcode, std::string>(OP_TXD, "TXD"),
  		std::pair<Opcode, std::string>(OP_TXQ, "TXQ"),
  		std::pair<Opcode, std::string>(OP_BMOV, "BMOV"),
  		std::pair<Opcode, std::string>(OP_BPT, "BPT"),
  		std::pair<Opcode, std::string>(OP_BRA, "BRA"),
  		std::pair<Opcode, std::string>(OP_BREAK, "BREAK"),
  		std::pair<Opcode, std::string>(OP_BRX, "BRX"),
  		std::pair<Opcode, std::string>(OP_BSSY, "BSSY"),
  		std::pair<Opcode, std::string>(OP_BSYNC, "BSYNC"),
  		std::pair<Opcode, std::string>(OP_CALL, "CALL"),
  		std::pair<Opcode, std::string>(OpcodeXIT, "EXIT"),
  		std::pair<Opcode, std::string>(OP_JMP, "JMP"),
  		std::pair<Opcode, std::string>(OP_JMX, "JMX"),
  		std::pair<Opcode, std::string>(OP_KILL, "KILL"),
  		std::pair<Opcode, std::string>(OP_NANOSLEEP, "NANOSLEEP"),
  		std::pair<Opcode, std::string>(OP_RET, "RET"),
  		std::pair<Opcode, std::string>(OP_RPCMOV, "RPCMOV"),
  		std::pair<Opcode, std::string>(OP_RTT, "RTT"),
  		std::pair<Opcode, std::string>(OP_WARPSYNC, "WARPSYNC"),
  		std::pair<Opcode, std::string>(OP_YIELD, "YIELD"),
  		std::pair<Opcode, std::string>(OP_B2R, "B2R"),
  		std::pair<Opcode, std::string>(OP_BAR, "BAR"),
  		std::pair<Opcode, std::string>(OP_CS2R, "CS2R"),
  		std::pair<Opcode, std::string>(OP_CSMTEST, "CSMTEST"),
  		std::pair<Opcode, std::string>(OP_DEPBAR, "DEPBAR"),
  		std::pair<Opcode, std::string>(OP_GETLMEMBASE, "GETLMEMBASE"),
  		std::pair<Opcode, std::string>(OP_LEPC, "LEPC"),
  		std::pair<Opcode, std::string>(OP_NOP, "NOP"),
  		std::pair<Opcode, std::string>(OP_PMTRIG, "PMTRIG"),
  		std::pair<Opcode, std::string>(OP_R2B, "R2B"),
  		std::pair<Opcode, std::string>(OP_S2R, "S2R"), 
  		std::pair<Opcode, std::string>(OP_SETCTAID, "SETCTAID"),
  		std::pair<Opcode, std::string>(OP_SETLMEMBASE, "SETLMEMBASE"),
  		std::pair<Opcode, std::string>(OP_VOTE, "VOTE"), 
  		std::pair<Opcode, std::string>(OP_VOTE_VTG, "VOTE_VTG"),
  		std::pair<Opcode, std::string>(OP_BMMA, "BMMA"),
  		std::pair<Opcode, std::string>(OP_MOVM, "MOVM"),
  		std::pair<Opcode, std::string>(OP_LDSM, "LDSM"),
  		std::pair<Opcode, std::string>(OP_R2UR, "R2UR"),
  		std::pair<Opcode, std::string>(OP_S2UR, "S2UR"),
  		std::pair<Opcode, std::string>(OP_UBMSK, "UBMSK"),
  		std::pair<Opcode, std::string>(OP_UBREV, "UBREV"),
  		std::pair<Opcode, std::string>(OP_UCLEA, "UCLEA"),
  		std::pair<Opcode, std::string>(OP_UFLO, "UFLO"),
  		std::pair<Opcode, std::string>(OP_UIADD3, "UIADD3"),
  		std::pair<Opcode, std::string>(OP_UIMAD, "UIMAD"),
  		std::pair<Opcode, std::string>(OP_UISETP, "UISETP"),
  		std::pair<Opcode, std::string>(OP_ULDC, "ULDC"),
  		std::pair<Opcode, std::string>(OP_ULEA, "ULEA"),
  		std::pair<Opcode, std::string>(OP_ULOP, "ULOP"),
  		std::pair<Opcode, std::string>(OP_ULOP3, "ULOP3"),
  		std::pair<Opcode, std::string>(OP_ULOP32I, "ULOP32I"),
  		std::pair<Opcode, std::string>(OP_UMOV, "UMOV"),
  		std::pair<Opcode, std::string>(OP_UP2UR, "UP2UR"),
  		std::pair<Opcode, std::string>(OP_UPLOP3, "UPLOP3"),
  		std::pair<Opcode, std::string>(OP_UPOPC, "UPOPC"),
  		std::pair<Opcode, std::string>(OP_UPRMT, "UPRMT"),
  		std::pair<Opcode, std::string>(OP_UPSETP, "UPSETP"),
  		std::pair<Opcode, std::string>(OP_UR2UP, "UR2UP"),
  		std::pair<Opcode, std::string>(OP_USEL, "USEL"),
  		std::pair<Opcode, std::string>(OP_USGXT, "USGXT"),
  		std::pair<Opcode, std::string>(OP_USHF, "USHF"),
  		std::pair<Opcode, std::string>(OP_USHL, "USHL"),
  		std::pair<Opcode, std::string>(OP_USHR, "USHR"),
  		std::pair<Opcode, std::string>(OP_VOTEU, "VOTEU"),
  		std::pair<Opcode, std::string>(OP_SUATOM, "SUATOM"),
  		std::pair<Opcode, std::string>(OP_SULD, "SULD"),
  		std::pair<Opcode, std::string>(OP_SURED, "SURED"),
  		std::pair<Opcode, std::string>(OP_SUST, "SUST"),
  		std::pair<Opcode, std::string>(OP_BRXU, "BRXU"),
  		std::pair<Opcode, std::string>(OP_JMXU, "JMXU"),
    };

	inline std::ostream & operator<<(std::ostream & os, const Opcode & op) {
		auto it = op2str_tab.find(op);
		if (it == op2str_tab.end()) {
        	throw std::invalid_argument("[op2str] Invalid input op.");
		}
		os << it->second;
		return os;
	}

	inline std::string op2str(Opcode op) {
		auto it = op2str_tab.find(op);
		if (it == op2str_tab.end()) {
        	throw std::invalid_argument("[op2str] Invalid op key.");
		}
		return it->second;
	}

    inline const std::unordered_map<std::string, Opcode> str2op_tab {
		std::pair<std::string, Opcode>("FADD", OP_FADD),
    	std::pair<std::string, Opcode>("FADD32I", OP_FADD32I),
    	std::pair<std::string, Opcode>("FCHK", OP_FCHK),
    	std::pair<std::string, Opcode>("FFMA32I", OP_FFMA32I),
    	std::pair<std::string, Opcode>("FFMA", OP_FFMA),
    	std::pair<std::string, Opcode>("FMNMX", OP_FMNMX),
    	std::pair<std::string, Opcode>("FMUL", OP_FMUL),
    	std::pair<std::string, Opcode>("FMUL32I", OP_FMUL32I),
    	std::pair<std::string, Opcode>("FSEL", OP_FSEL),
    	std::pair<std::string, Opcode>("FSET", OP_FSET),
    	std::pair<std::string, Opcode>("FSETP", OP_FSETP),
    	std::pair<std::string, Opcode>("FSWZADD", OP_FSWZADD),
    	std::pair<std::string, Opcode>("MUFU", OP_MUFU),
    	std::pair<std::string, Opcode>("HADD2", OP_HADD2),
    	std::pair<std::string, Opcode>("HADD2_32I", OP_HADD2_32I),
    	std::pair<std::string, Opcode>("HFMA2", OP_HFMA2),
    	std::pair<std::string, Opcode>("HFMA2_32I", OP_HFMA2_32I),
    	std::pair<std::string, Opcode>("HMUL2", OP_HMUL2),
    	std::pair<std::string, Opcode>("HMUL2_32I", OP_HMUL2_32I),
    	std::pair<std::string, Opcode>("HSET2", OP_HSET2),
    	std::pair<std::string, Opcode>("HSETP2", OP_HSETP2),
    	std::pair<std::string, Opcode>("HMMA", OP_HMMA),
    	std::pair<std::string, Opcode>("DADD", OP_DADD),
    	std::pair<std::string, Opcode>("DFMA", OP_DFMA),
    	std::pair<std::string, Opcode>("DMUL", OP_DMUL),
    	std::pair<std::string, Opcode>("DSETP", OP_DSETP),
    	std::pair<std::string, Opcode>("BMSK", OP_BMSK),
    	std::pair<std::string, Opcode>("BREV", OP_BREV),
    	std::pair<std::string, Opcode>("FLO", OP_FLO),
    	std::pair<std::string, Opcode>("IABS", OP_IABS),
    	std::pair<std::string, Opcode>("IADD", OP_IADD),
    	std::pair<std::string, Opcode>("IADD3", OP_IADD3),
    	std::pair<std::string, Opcode>("IADD32I", OP_IADD32I),
    	std::pair<std::string, Opcode>("IDP", OP_IDP),
    	std::pair<std::string, Opcode>("IDP4A", OP_IDP4A),
    	std::pair<std::string, Opcode>("IMAD", OP_IMAD),
    	std::pair<std::string, Opcode>("IMMA", OP_IMMA),
    	std::pair<std::string, Opcode>("IMNMX", OP_IMNMX),
  		std::pair<std::string, Opcode>("IMUL", OP_IMUL),
    	std::pair<std::string, Opcode>("IMUL32I", OP_IMUL32I),
    	std::pair<std::string, Opcode>("ISCADD", OP_ISCADD),
    	std::pair<std::string, Opcode>("ISCADD32I", OP_ISCADD32I),
    	std::pair<std::string, Opcode>("ISETP", OP_ISETP),
    	std::pair<std::string, Opcode>("LEA", OP_LEA),
    	std::pair<std::string, Opcode>("LOP", OP_LOP),
    	std::pair<std::string, Opcode>("LOP3", OP_LOP3),
    	std::pair<std::string, Opcode>("LOP32I", OP_LOP32I),
    	std::pair<std::string, Opcode>("POPC", OP_POPC),
    	std::pair<std::string, Opcode>("SHF", OP_SHF),
    	std::pair<std::string, Opcode>("SHR", OP_SHR),
    	std::pair<std::string, Opcode>("VABSDIFF", OP_VABSDIFF),
    	std::pair<std::string, Opcode>("VABSDIFF4", OP_VABSDIFF4),
    	std::pair<std::string, Opcode>("VADD", OP_VADD),
  		std::pair<std::string, Opcode>("F2F", OP_F2F),
    	std::pair<std::string, Opcode>("F2I", OP_F2I),
    	std::pair<std::string, Opcode>("I2F", OP_I2F),
    	std::pair<std::string, Opcode>("I2I", OP_I2I),
    	std::pair<std::string, Opcode>("I2IP", OP_I2IP),
    	std::pair<std::string, Opcode>("FRND", OP_FRND),
    	std::pair<std::string, Opcode>("MOV", OP_MOV),
    	std::pair<std::string, Opcode>("MOV32I", OP_MOV32I),
    	std::pair<std::string, Opcode>("PRMT", OP_PRMT),
    	std::pair<std::string, Opcode>("SEL", OP_SEL),
    	std::pair<std::string, Opcode>("SGXT", OP_SGXT),
    	std::pair<std::string, Opcode>("SHFL", OP_SHFL),
    	std::pair<std::string, Opcode>("PLOP3", OP_PLOP3),
    	std::pair<std::string, Opcode>("PSETP", OP_PSETP),
    	std::pair<std::string, Opcode>("P2R", OP_P2R),
    	std::pair<std::string, Opcode>("R2P", OP_R2P),
    	std::pair<std::string, Opcode>("LD", OP_LD),
    	std::pair<std::string, Opcode>("LDC", OP_LDC),
  		std::pair<std::string, Opcode>("LDG", OP_LDG),
    	std::pair<std::string, Opcode>("LDL", OP_LDL),
    	std::pair<std::string, Opcode>("LDS", OP_LDS),
    	std::pair<std::string, Opcode>("ST", OP_ST),
    	std::pair<std::string, Opcode>("STG", OP_STG),
    	std::pair<std::string, Opcode>("STL", OP_STL),
    	std::pair<std::string, Opcode>("STS", OP_STS),
    	std::pair<std::string, Opcode>("MATCH", OP_MATCH),
    	std::pair<std::string, Opcode>("QSPC", OP_QSPC),
    	std::pair<std::string, Opcode>("ATOM", OP_ATOM),
    	std::pair<std::string, Opcode>("ATOMS", OP_ATOMS),
    	std::pair<std::string, Opcode>("ATOMG", OP_ATOMG),
    	std::pair<std::string, Opcode>("RED", OP_RED),
    	std::pair<std::string, Opcode>("CCTL", OP_CCTL),
    	std::pair<std::string, Opcode>("CCTLL", OP_CCTLL),
    	std::pair<std::string, Opcode>("ERRBAR", OpcodeRRBAR),
    	std::pair<std::string, Opcode>("MEMBAR", OP_MEMBAR),
    	std::pair<std::string, Opcode>("CCTLT", OP_CCTLT),
    	std::pair<std::string, Opcode>("TEX", OP_TEX),
    	std::pair<std::string, Opcode>("TLD", OP_TLD),
    	std::pair<std::string, Opcode>("TLD4", OP_TLD4),
    	std::pair<std::string, Opcode>("TMML", OP_TMML),
    	std::pair<std::string, Opcode>("TXD", OP_TXD),
    	std::pair<std::string, Opcode>("TXQ", OP_TXQ),
    	std::pair<std::string, Opcode>("BMOV", OP_BMOV),
  		std::pair<std::string, Opcode>("BPT", OP_BPT),
    	std::pair<std::string, Opcode>("BRA", OP_BRA),
    	std::pair<std::string, Opcode>("BREAK", OP_BREAK),
    	std::pair<std::string, Opcode>("BRX", OP_BRX),
    	std::pair<std::string, Opcode>("BSSY", OP_BSSY),
    	std::pair<std::string, Opcode>("BSYNC", OP_BSYNC),
    	std::pair<std::string, Opcode>("CALL", OP_CALL),
    	std::pair<std::string, Opcode>("EXIT", OpcodeXIT),
    	std::pair<std::string, Opcode>("JMP", OP_JMP),
    	std::pair<std::string, Opcode>("JMX", OP_JMX),
    	std::pair<std::string, Opcode>("KILL", OP_KILL),
    	std::pair<std::string, Opcode>("NANOSLEEP", OP_NANOSLEEP),
    	std::pair<std::string, Opcode>("RET", OP_RET),
    	std::pair<std::string, Opcode>("RPCMOV", OP_RPCMOV),
    	std::pair<std::string, Opcode>("RTT", OP_RTT),
    	std::pair<std::string, Opcode>("WARPSYNC", OP_WARPSYNC),
    	std::pair<std::string, Opcode>("YIELD", OP_YIELD),
    	std::pair<std::string, Opcode>("B2R", OP_B2R),
    	std::pair<std::string, Opcode>("BAR", OP_BAR),
    	std::pair<std::string, Opcode>("CS2R", OP_CS2R),
    	std::pair<std::string, Opcode>("CSMTEST", OP_CSMTEST),
    	std::pair<std::string, Opcode>("DEPBAR", OP_DEPBAR),
    	std::pair<std::string, Opcode>("GETLMEMBASE", OP_GETLMEMBASE),
    	std::pair<std::string, Opcode>("LEPC", OP_LEPC),
    	std::pair<std::string, Opcode>("NOP", OP_NOP),
    	std::pair<std::string, Opcode>("PMTRIG", OP_PMTRIG),
    	std::pair<std::string, Opcode>("R2B", OP_R2B),
    	std::pair<std::string, Opcode>("S2R", OP_S2R),
    	std::pair<std::string, Opcode>("SETCTAID", OP_SETCTAID),
    	std::pair<std::string, Opcode>("SETLMEMBASE", OP_SETLMEMBASE),
    	std::pair<std::string, Opcode>("VOTE", OP_VOTE),
    	std::pair<std::string, Opcode>("VOTE_VTG", OP_VOTE_VTG),
    	std::pair<std::string, Opcode>("BMMA", OP_BMMA),
    	std::pair<std::string, Opcode>("MOVM", OP_MOVM),
    	std::pair<std::string, Opcode>("LDSM", OP_LDSM),
    	std::pair<std::string, Opcode>("R2UR", OP_R2UR),
    	std::pair<std::string, Opcode>("S2UR", OP_S2UR),
    	std::pair<std::string, Opcode>("UBMSK", OP_UBMSK),
    	std::pair<std::string, Opcode>("UBREV", OP_UBREV),
    	std::pair<std::string, Opcode>("UCLEA", OP_UCLEA),
    	std::pair<std::string, Opcode>("UFLO", OP_UFLO),
    	std::pair<std::string, Opcode>("UIADD3", OP_UIADD3),
    	std::pair<std::string, Opcode>("UIMAD", OP_UIMAD),
    	std::pair<std::string, Opcode>("UISETP", OP_UISETP),
    	std::pair<std::string, Opcode>("ULDC", OP_ULDC),
    	std::pair<std::string, Opcode>("ULEA", OP_ULEA),
    	std::pair<std::string, Opcode>("ULOP", OP_ULOP),
    	std::pair<std::string, Opcode>("ULOP3", OP_ULOP3),
    	std::pair<std::string, Opcode>("ULOP32I", OP_ULOP32I),
    	std::pair<std::string, Opcode>("UMOV", OP_UMOV),
    	std::pair<std::string, Opcode>("UP2UR", OP_UP2UR),
    	std::pair<std::string, Opcode>("UPLOP3", OP_UPLOP3),
    	std::pair<std::string, Opcode>("UPOPC", OP_UPOPC),
    	std::pair<std::string, Opcode>("UPRMT", OP_UPRMT),
    	std::pair<std::string, Opcode>("UPSETP", OP_UPSETP),
    	std::pair<std::string, Opcode>("UR2UP", OP_UR2UP),
    	std::pair<std::string, Opcode>("USEL", OP_USEL),
    	std::pair<std::string, Opcode>("USGXT", OP_USGXT),
    	std::pair<std::string, Opcode>("USHF", OP_USHF),
    	std::pair<std::string, Opcode>("USHL", OP_USHL),
    	std::pair<std::string, Opcode>("USHR", OP_USHR),
    	std::pair<std::string, Opcode>("VOTEU", OP_VOTEU),
    	std::pair<std::string, Opcode>("SUATOM", OP_SUATOM),
    	std::pair<std::string, Opcode>("SULD", OP_SULD),
    	std::pair<std::string, Opcode>("SURED", OP_SURED),
    	std::pair<std::string, Opcode>("SUST", OP_SUST),
    	std::pair<std::string, Opcode>("BRXU", OP_BRXU),
    	std::pair<std::string, Opcode>("JMXU", OP_JMXU)
    };

	inline Opcode str2op(const std::string & s) {
    	auto it = str2op_tab.find(s);
    	if(it == str2op_tab.end()) {
        	throw std::invalid_argument("[str2op] Invalid string key.");
    	}
		return it->second;
	}


}; /* namespace op */