// NVIDIA Turing SASS model
// Qiran Qian, qiranq@kth.se

#ifndef TRACE_OPCODE_H
#define TRACE_OPCODE_H

#include <unordered_map>
#include <stdexcept>

enum InstOpcode {
	OP_VOID = 0, // This Op doesn't exist, but kept for implementing the parser
	
	// Basic (Volta) SASS Opcode
	OP_FADD = 1,
  	OP_FADD32I,
  	OP_FCHK,
  	OP_FFMA32I,
  	OP_FFMA,
  	OP_FMNMX,
  	OP_FMUL,
  	OP_FMUL32I,
  	OP_FSEL,
  	OP_FSET,
  	OP_FSETP,
  	OP_FSWZADD,
  	OP_MUFU,
  	OP_HADD2,
  	OP_HADD2_32I,
  	OP_HFMA2,
  	OP_HFMA2_32I,
  	OP_HMUL2,
  	OP_HMUL2_32I,
  	OP_HSET2,
  	OP_HSETP2,
  	OP_HMMA,
  	OP_DADD,
  	OP_DFMA,
  	OP_DMUL,
  	OP_DSETP,
  	OP_BMSK,
  	OP_BREV,
  	OP_FLO,
  	OP_IABS,
  	OP_IADD,
  	OP_IADD3,
  	OP_IADD32I,
  	OP_IDP,
	OP_IDP4A,
	OP_IMAD,	
	OP_IMMA,
	OP_IMNMX,
	OP_IMUL,
	OP_IMUL32I,	
	OP_ISCADD,
  	OP_ISCADD32I,
  	OP_ISETP,
  	OP_LEA,
  	OP_LOP,
  	OP_LOP3,
  	OP_LOP32I,
  	OP_POPC,
  	OP_SHF,
  	OP_SHR,
  	OP_VABSDIFF,
  	OP_VABSDIFF4,
  	OP_VADD,
  	OP_F2F,
  	OP_F2I,
  	OP_I2F,
  	OP_I2I,
  	OP_I2IP,
  	OP_FRND,
  	OP_MOV,
  	OP_MOV32I,
  	OP_PRMT,
  	OP_SEL,
  	OP_SGXT,
  	OP_SHFL,
  	OP_PLOP3,
  	OP_PSETP,
  	OP_P2R,
  	OP_R2P,
  	OP_LD,
  	OP_LDC,
  	OP_LDG,
  	OP_LDL,
  	OP_LDS,
  	OP_ST,
  	OP_STG,
  	OP_STL,
  	OP_STS,
  	OP_MATCH,
  	OP_QSPC,
  	OP_ATOM,
  	OP_ATOMS,
  	OP_ATOMG,
  	OP_RED,
  	OP_CCTL,
  	OP_CCTLL,
  	OP_ERRBAR,
  	OP_MEMBAR,
  	OP_CCTLT,
  	OP_TEX,
  	OP_TLD,
  	OP_TLD4,
  	OP_TMML,
  	OP_TXD,
  	OP_TXQ,
  	OP_BMOV,
  	OP_BPT,
  	OP_BRA,
  	OP_BREAK,
  	OP_BRX,
  	OP_BSSY,
  	OP_BSYNC,
  	OP_CALL,
  	OP_EXIT,
  	OP_JMP,
  	OP_JMX,
  	OP_KILL,
  	OP_NANOSLEEP,
  	OP_RET,
  	OP_RPCMOV,
  	OP_RTT,
  	OP_WARPSYNC,
  	OP_YIELD,
  	OP_B2R,
  	OP_BAR,
  	OP_CS2R,
  	OP_CSMTEST,
  	OP_DEPBAR,
  	OP_GETLMEMBASE,
  	OP_LEPC,
  	OP_NOP,
  	OP_PMTRIG,
  	OP_R2B,
  	OP_S2R,
  	OP_SETCTAID,
  	OP_SETLMEMBASE,
  	OP_VOTE,
  	OP_VOTE_VTG,

	// Unique Opcodes for Turing SASS		
  	OP_BMMA,
  	OP_MOVM,
  	OP_LDSM,
  	OP_R2UR,
  	OP_S2UR,
  	OP_UBMSK,
  	OP_UBREV,
  	OP_UCLEA,
  	OP_UFLO,
  	OP_UIADD3,
  	OP_UIMAD,
  	OP_UISETP,
  	OP_ULDC,
  	OP_ULEA,
  	OP_ULOP,
  	OP_ULOP3,
  	OP_ULOP32I,
  	OP_UMOV,
  	OP_UP2UR,
  	OP_UPLOP3,
  	OP_UPOPC,
  	OP_UPRMT,
  	OP_UPSETP,
  	OP_UR2UP,
  	OP_USEL,
  	OP_USGXT,
  	OP_USHF,
  	OP_USHL,
  	OP_USHR,
  	OP_VOTEU,
  	OP_SUATOM,
  	OP_SULD,
  	OP_SURED,
  	OP_SUST,
  	OP_BRXU,
  	OP_JMXU,

	// Total number of Opcodes
	SASS_NUM_OPCODES
};

std::string MapOpcode2String(const InstOpcode & instOp) {
    std::unordered_map<InstOpcode, std::string> hashMap = {
    	std::pair<InstOpcode, std::string>(OP_FADD, "FADD"),
  		std::pair<InstOpcode, std::string>(OP_FADD32I, "FADD32I"),
  		std::pair<InstOpcode, std::string>(OP_FCHK, "FCHK"),
  		std::pair<InstOpcode, std::string>(OP_FFMA32I, "FFMA32I"),
  		std::pair<InstOpcode, std::string>(OP_FFMA, "FFMA"),
  		std::pair<InstOpcode, std::string>(OP_FMNMX, "FMNMX"),
  		std::pair<InstOpcode, std::string>(OP_FMUL, "FMUL"),
  		std::pair<InstOpcode, std::string>(OP_FMUL32I, "FMUL32I"),
  		std::pair<InstOpcode, std::string>(OP_FSEL, "FSEL"),
  		std::pair<InstOpcode, std::string>(OP_FSET, "FSET"),
  		std::pair<InstOpcode, std::string>(OP_FSETP, "FSETP"),
  		std::pair<InstOpcode, std::string>(OP_FSWZADD, "FSWZADD"),
  		std::pair<InstOpcode, std::string>(OP_MUFU, "MUFU"),
  		std::pair<InstOpcode, std::string>(OP_HADD2, "HADD2"),
  		std::pair<InstOpcode, std::string>(OP_HADD2_32I, "HADD2_32I"),
  		std::pair<InstOpcode, std::string>(OP_HFMA2, "HFMA2"),
  		std::pair<InstOpcode, std::string>(OP_HFMA2_32I, "HFMA2_32I"),
  		std::pair<InstOpcode, std::string>(OP_HMUL2, "HMUL2"),
  		std::pair<InstOpcode, std::string>(OP_HMUL2_32I, "HMUL2_32I"),
  		std::pair<InstOpcode, std::string>(OP_HSET2, "HSET2"),
  		std::pair<InstOpcode, std::string>(OP_HSETP2, "HSETP2"),
  		std::pair<InstOpcode, std::string>(OP_HMMA, "HMMA"),
  		std::pair<InstOpcode, std::string>(OP_DADD, "DADD"),
  		std::pair<InstOpcode, std::string>(OP_DFMA, "DFMA"),
  		std::pair<InstOpcode, std::string>(OP_DMUL, "DMUL"),
  		std::pair<InstOpcode, std::string>(OP_DSETP, "DSETP"),
  		std::pair<InstOpcode, std::string>(OP_BMSK, "BMSK"),
  		std::pair<InstOpcode, std::string>(OP_BREV, "BREV"),
  		std::pair<InstOpcode, std::string>(OP_FLO, "FLO"),
  		std::pair<InstOpcode, std::string>(OP_IABS, "IABS"),
  		std::pair<InstOpcode, std::string>(OP_IADD, "IADD"),
  		std::pair<InstOpcode, std::string>(OP_IADD3, "IADD3"),
  		std::pair<InstOpcode, std::string>(OP_IADD32I, "IADD32I"),
  		std::pair<InstOpcode, std::string>(OP_IDP, "IDP"),
		std::pair<InstOpcode, std::string>(OP_IDP4A, "IDP4A"),
		std::pair<InstOpcode, std::string>(OP_IMAD, "IMAD"),	
		std::pair<InstOpcode, std::string>(OP_IMMA, "IMMA"),
		std::pair<InstOpcode, std::string>(OP_IMNMX, "IMNMX"),
		std::pair<InstOpcode, std::string>(OP_IMUL, "IMUL"),
		std::pair<InstOpcode, std::string>(OP_IMUL32I,	"IMUL32I"),
		std::pair<InstOpcode, std::string>(OP_ISCADD, "ISCADD"),
  		std::pair<InstOpcode, std::string>(OP_ISCADD32I, "ISCADD32I"),
  		std::pair<InstOpcode, std::string>(OP_ISETP, "ISETP"),
  		std::pair<InstOpcode, std::string>(OP_LEA, "LEA"),
  		std::pair<InstOpcode, std::string>(OP_LOP, "LOP"),
    	std::pair<InstOpcode, std::string>(OP_LOP3, "LOP3"),
  		std::pair<InstOpcode, std::string>(OP_LOP32I, "LOP32I"),
  		std::pair<InstOpcode, std::string>(OP_POPC, "POPC"),
  		std::pair<InstOpcode, std::string>(OP_SHF, "SHF"),
  		std::pair<InstOpcode, std::string>(OP_SHR, "SHR"),
  		std::pair<InstOpcode, std::string>(OP_VABSDIFF, "VABSDIFF"),
  		std::pair<InstOpcode, std::string>(OP_VABSDIFF4, "VABSDIFF4"),
  		std::pair<InstOpcode, std::string>(OP_VADD, "VADD"),
  		std::pair<InstOpcode, std::string>(OP_F2F, "F2F"),
  		std::pair<InstOpcode, std::string>(OP_F2I, "F2I"),
  		std::pair<InstOpcode, std::string>(OP_I2F, "I2F"),
  		std::pair<InstOpcode, std::string>(OP_I2I, "I2I"),
  		std::pair<InstOpcode, std::string>(OP_I2IP, "I2IP"),
  		std::pair<InstOpcode, std::string>(OP_FRND, "FRND"),
  		std::pair<InstOpcode, std::string>(OP_MOV, "MOV"),
  		std::pair<InstOpcode, std::string>(OP_MOV32I, "MOV32I"),
  		std::pair<InstOpcode, std::string>(OP_PRMT, "PRMT"),
  		std::pair<InstOpcode, std::string>(OP_SEL, "SEL"),
  		std::pair<InstOpcode, std::string>(OP_SGXT, "SGXT"),
  		std::pair<InstOpcode, std::string>(OP_SHFL, "SHFL"),
  		std::pair<InstOpcode, std::string>(OP_PLOP3, "PLOP3"),
  		std::pair<InstOpcode, std::string>(OP_PSETP, "PSETP"),
  		std::pair<InstOpcode, std::string>(OP_P2R, "P2R"),
  		std::pair<InstOpcode, std::string>(OP_R2P, "R2P"),
  		std::pair<InstOpcode, std::string>(OP_LD, "LD"),
  		std::pair<InstOpcode, std::string>(OP_LDC, "LDC"),
  		std::pair<InstOpcode, std::string>(OP_LDG, "LDG"),
  		std::pair<InstOpcode, std::string>(OP_LDL, "LDL"),
  		std::pair<InstOpcode, std::string>(OP_LDS, "LDS"),
  		std::pair<InstOpcode, std::string>(OP_ST, "ST"),
  		std::pair<InstOpcode, std::string>(OP_STG, "STG"),
  		std::pair<InstOpcode, std::string>(OP_STL, "STL"),
  		std::pair<InstOpcode, std::string>(OP_STS, "STS"),
  		std::pair<InstOpcode, std::string>(OP_MATCH, "MATCH"),
  		std::pair<InstOpcode, std::string>(OP_QSPC, "QSPC"),
  		std::pair<InstOpcode, std::string>(OP_ATOM, "ATOM"),
  		std::pair<InstOpcode, std::string>(OP_ATOMS, "ATOMS"),
  		std::pair<InstOpcode, std::string>(OP_ATOMG, "ATOMG"),
  		std::pair<InstOpcode, std::string>(OP_RED, "RED"),
  		std::pair<InstOpcode, std::string>(OP_CCTL, "CCTL"),
  		std::pair<InstOpcode, std::string>(OP_CCTLL, "CCTLL"),
  		std::pair<InstOpcode, std::string>(OP_ERRBAR, "ERRBAR"),
  		std::pair<InstOpcode, std::string>(OP_MEMBAR, "MEMBAR"),
  		std::pair<InstOpcode, std::string>(OP_CCTLT, "CCTLT"),
  		std::pair<InstOpcode, std::string>(OP_TEX, "TEX"),
  		std::pair<InstOpcode, std::string>(OP_TLD, "TLD"),
  		std::pair<InstOpcode, std::string>(OP_TLD4, "TLD4"),
  		std::pair<InstOpcode, std::string>(OP_TMML, "TMML"),
  		std::pair<InstOpcode, std::string>(OP_TXD, "TXD"),
  		std::pair<InstOpcode, std::string>(OP_TXQ, "TXQ"),
  		std::pair<InstOpcode, std::string>(OP_BMOV, "BMOV"),
  		std::pair<InstOpcode, std::string>(OP_BPT, "BPT"),
  		std::pair<InstOpcode, std::string>(OP_BRA, "BRA"),
  		std::pair<InstOpcode, std::string>(OP_BREAK, "BREAK"),
  		std::pair<InstOpcode, std::string>(OP_BRX, "BRX"),
  		std::pair<InstOpcode, std::string>(OP_BSSY, "BSSY"),
  		std::pair<InstOpcode, std::string>(OP_BSYNC, "BSYNC"),
  		std::pair<InstOpcode, std::string>(OP_CALL, "CALL"),
  		std::pair<InstOpcode, std::string>(OP_EXIT, "EXIT"),
  		std::pair<InstOpcode, std::string>(OP_JMP, "JMP"),
  		std::pair<InstOpcode, std::string>(OP_JMX, "JMX"),
  		std::pair<InstOpcode, std::string>(OP_KILL, "KILL"),
  		std::pair<InstOpcode, std::string>(OP_NANOSLEEP, "NANOSLEEP"),
  		std::pair<InstOpcode, std::string>(OP_RET, "RET"),
  		std::pair<InstOpcode, std::string>(OP_RPCMOV, "RPCMOV"),
  		std::pair<InstOpcode, std::string>(OP_RTT, "RTT"),
  		std::pair<InstOpcode, std::string>(OP_WARPSYNC, "WARPSYNC"),
  		std::pair<InstOpcode, std::string>(OP_YIELD, "YIELD"),
  		std::pair<InstOpcode, std::string>(OP_B2R, "B2R"),
  		std::pair<InstOpcode, std::string>(OP_BAR, "BAR"),
  		std::pair<InstOpcode, std::string>(OP_CS2R, "CS2R"),
  		std::pair<InstOpcode, std::string>(OP_CSMTEST, "CSMTEST"),
  		std::pair<InstOpcode, std::string>(OP_DEPBAR, "DEPBAR"),
  		std::pair<InstOpcode, std::string>(OP_GETLMEMBASE, "GETLMEMBASE"),
  		std::pair<InstOpcode, std::string>(OP_LEPC, "LEPC"),
  		std::pair<InstOpcode, std::string>(OP_NOP, "NOP"),
  		std::pair<InstOpcode, std::string>(OP_PMTRIG, "PMTRIG"),
  		std::pair<InstOpcode, std::string>(OP_R2B, "R2B"),
  		std::pair<InstOpcode, std::string>(OP_S2R, "S2R"), 
  		std::pair<InstOpcode, std::string>(OP_SETCTAID, "SETCTAID"),
  		std::pair<InstOpcode, std::string>(OP_SETLMEMBASE, "SETLMEMBASE"),
  		std::pair<InstOpcode, std::string>(OP_VOTE, "VOTE"), 
  		std::pair<InstOpcode, std::string>(OP_VOTE_VTG, "VOTE_VTG"),
  		std::pair<InstOpcode, std::string>(OP_BMMA, "BMMA"),
  		std::pair<InstOpcode, std::string>(OP_MOVM, "MOVM"),
  		std::pair<InstOpcode, std::string>(OP_LDSM, "LDSM"),
  		std::pair<InstOpcode, std::string>(OP_R2UR, "R2UR"),
  		std::pair<InstOpcode, std::string>(OP_S2UR, "S2UR"),
  		std::pair<InstOpcode, std::string>(OP_UBMSK, "UBMSK"),
  		std::pair<InstOpcode, std::string>(OP_UBREV, "UBREV"),
  		std::pair<InstOpcode, std::string>(OP_UCLEA, "UCLEA"),
  		std::pair<InstOpcode, std::string>(OP_UFLO, "UFLO"),
  		std::pair<InstOpcode, std::string>(OP_UIADD3, "UIADD3"),
  		std::pair<InstOpcode, std::string>(OP_UIMAD, "UIMAD"),
  		std::pair<InstOpcode, std::string>(OP_UISETP, "UISETP"),
  		std::pair<InstOpcode, std::string>(OP_ULDC, "ULDC"),
  		std::pair<InstOpcode, std::string>(OP_ULEA, "ULEA"),
  		std::pair<InstOpcode, std::string>(OP_ULOP, "ULOP"),
  		std::pair<InstOpcode, std::string>(OP_ULOP3, "ULOP3"),
  		std::pair<InstOpcode, std::string>(OP_ULOP32I, "ULOP32I"),
  		std::pair<InstOpcode, std::string>(OP_UMOV, "UMOV"),
  		std::pair<InstOpcode, std::string>(OP_UP2UR, "UP2UR"),
  		std::pair<InstOpcode, std::string>(OP_UPLOP3, "UPLOP3"),
  		std::pair<InstOpcode, std::string>(OP_UPOPC, "UPOPC"),
  		std::pair<InstOpcode, std::string>(OP_UPRMT, "UPRMT"),
  		std::pair<InstOpcode, std::string>(OP_UPSETP, "UPSETP"),
  		std::pair<InstOpcode, std::string>(OP_UR2UP, "UR2UP"),
  		std::pair<InstOpcode, std::string>(OP_USEL, "USEL"),
  		std::pair<InstOpcode, std::string>(OP_USGXT, "USGXT"),
  		std::pair<InstOpcode, std::string>(OP_USHF, "USHF"),
  		std::pair<InstOpcode, std::string>(OP_USHL, "USHL"),
  		std::pair<InstOpcode, std::string>(OP_USHR, "USHR"),
  		std::pair<InstOpcode, std::string>(OP_VOTEU, "VOTEU"),
  		std::pair<InstOpcode, std::string>(OP_SUATOM, "SUATOM"),
  		std::pair<InstOpcode, std::string>(OP_SULD, "SULD"),
  		std::pair<InstOpcode, std::string>(OP_SURED, "SURED"),
  		std::pair<InstOpcode, std::string>(OP_SUST, "SUST"),
  		std::pair<InstOpcode, std::string>(OP_BRXU, "BRXU"),
  		std::pair<InstOpcode, std::string>(OP_JMXU, "JMXU"),
    };

    auto it = hashMap.find(instOp);
    if(it == hashMap.end()) {
        throw std::invalid_argument("[MapOpcode2String] Invalid input Opcode.");
    }
    return it->second;
}

InstOpcode MapString2Opcode(std::string str) {
    std::unordered_map<std::string, InstOpcode> hashMap = {
		std::pair<std::string, InstOpcode>("FADD", OP_FADD),
    	std::pair<std::string, InstOpcode>("FADD32I", OP_FADD32I),
    	std::pair<std::string, InstOpcode>("FCHK", OP_FCHK),
    	std::pair<std::string, InstOpcode>("FFMA32I", OP_FFMA32I),
    	std::pair<std::string, InstOpcode>("FFMA", OP_FFMA),
    	std::pair<std::string, InstOpcode>("FMNMX", OP_FMNMX),
    	std::pair<std::string, InstOpcode>("FMUL", OP_FMUL),
    	std::pair<std::string, InstOpcode>("FMUL32I", OP_FMUL32I),
    	std::pair<std::string, InstOpcode>("FSEL", OP_FSEL),
    	std::pair<std::string, InstOpcode>("FSET", OP_FSET),
    	std::pair<std::string, InstOpcode>("FSETP", OP_FSETP),
    	std::pair<std::string, InstOpcode>("FSWZADD", OP_FSWZADD),
    	std::pair<std::string, InstOpcode>("MUFU", OP_MUFU),
    	std::pair<std::string, InstOpcode>("HADD2", OP_HADD2),
    	std::pair<std::string, InstOpcode>("HADD2_32I", OP_HADD2_32I),
    	std::pair<std::string, InstOpcode>("HFMA2", OP_HFMA2),
    	std::pair<std::string, InstOpcode>("HFMA2_32I", OP_HFMA2_32I),
    	std::pair<std::string, InstOpcode>("HMUL2", OP_HMUL2),
    	std::pair<std::string, InstOpcode>("HMUL2_32I", OP_HMUL2_32I),
    	std::pair<std::string, InstOpcode>("HSET2", OP_HSET2),
    	std::pair<std::string, InstOpcode>("HSETP2", OP_HSETP2),
    	std::pair<std::string, InstOpcode>("HMMA", OP_HMMA),
    	std::pair<std::string, InstOpcode>("DADD", OP_DADD),
    	std::pair<std::string, InstOpcode>("DFMA", OP_DFMA),
    	std::pair<std::string, InstOpcode>("DMUL", OP_DMUL),
    	std::pair<std::string, InstOpcode>("DSETP", OP_DSETP),
    	std::pair<std::string, InstOpcode>("BMSK", OP_BMSK),
    	std::pair<std::string, InstOpcode>("BREV", OP_BREV),
    	std::pair<std::string, InstOpcode>("FLO", OP_FLO),
    	std::pair<std::string, InstOpcode>("IABS", OP_IABS),
    	std::pair<std::string, InstOpcode>("IADD", OP_IADD),
    	std::pair<std::string, InstOpcode>("IADD3", OP_IADD3),
    	std::pair<std::string, InstOpcode>("IADD32I", OP_IADD32I),
    	std::pair<std::string, InstOpcode>("IDP", OP_IDP),
    	std::pair<std::string, InstOpcode>("IDP4A", OP_IDP4A),
    	std::pair<std::string, InstOpcode>("IMAD", OP_IMAD),
    	std::pair<std::string, InstOpcode>("IMMA", OP_IMMA),
    	std::pair<std::string, InstOpcode>("IMNMX", OP_IMNMX),
  		std::pair<std::string, InstOpcode>("IMUL", OP_IMUL),
    	std::pair<std::string, InstOpcode>("IMUL32I", OP_IMUL32I),
    	std::pair<std::string, InstOpcode>("ISCADD", OP_ISCADD),
    	std::pair<std::string, InstOpcode>("ISCADD32I", OP_ISCADD32I),
    	std::pair<std::string, InstOpcode>("ISETP", OP_ISETP),
    	std::pair<std::string, InstOpcode>("LEA", OP_LEA),
    	std::pair<std::string, InstOpcode>("LOP", OP_LOP),
    	std::pair<std::string, InstOpcode>("LOP3", OP_LOP3),
    	std::pair<std::string, InstOpcode>("LOP32I", OP_LOP32I),
    	std::pair<std::string, InstOpcode>("POPC", OP_POPC),
    	std::pair<std::string, InstOpcode>("SHF", OP_SHF),
    	std::pair<std::string, InstOpcode>("SHR", OP_SHR),
    	std::pair<std::string, InstOpcode>("VABSDIFF", OP_VABSDIFF),
    	std::pair<std::string, InstOpcode>("VABSDIFF4", OP_VABSDIFF4),
    	std::pair<std::string, InstOpcode>("VADD", OP_VADD),
  		std::pair<std::string, InstOpcode>("F2F", OP_F2F),
    	std::pair<std::string, InstOpcode>("F2I", OP_F2I),
    	std::pair<std::string, InstOpcode>("I2F", OP_I2F),
    	std::pair<std::string, InstOpcode>("I2I", OP_I2I),
    	std::pair<std::string, InstOpcode>("I2IP", OP_I2IP),
    	std::pair<std::string, InstOpcode>("FRND", OP_FRND),
    	std::pair<std::string, InstOpcode>("MOV", OP_MOV),
    	std::pair<std::string, InstOpcode>("MOV32I", OP_MOV32I),
    	std::pair<std::string, InstOpcode>("PRMT", OP_PRMT),
    	std::pair<std::string, InstOpcode>("SEL", OP_SEL),
    	std::pair<std::string, InstOpcode>("SGXT", OP_SGXT),
    	std::pair<std::string, InstOpcode>("SHFL", OP_SHFL),
    	std::pair<std::string, InstOpcode>("PLOP3", OP_PLOP3),
    	std::pair<std::string, InstOpcode>("PSETP", OP_PSETP),
    	std::pair<std::string, InstOpcode>("P2R", OP_P2R),
    	std::pair<std::string, InstOpcode>("R2P", OP_R2P),
    	std::pair<std::string, InstOpcode>("LD", OP_LD),
    	std::pair<std::string, InstOpcode>("LDC", OP_LDC),
  		std::pair<std::string, InstOpcode>("LDG", OP_LDG),
    	std::pair<std::string, InstOpcode>("LDL", OP_LDL),
    	std::pair<std::string, InstOpcode>("LDS", OP_LDS),
    	std::pair<std::string, InstOpcode>("ST", OP_ST),
    	std::pair<std::string, InstOpcode>("STG", OP_STG),
    	std::pair<std::string, InstOpcode>("STL", OP_STL),
    	std::pair<std::string, InstOpcode>("STS", OP_STS),
    	std::pair<std::string, InstOpcode>("MATCH", OP_MATCH),
    	std::pair<std::string, InstOpcode>("QSPC", OP_QSPC),
    	std::pair<std::string, InstOpcode>("ATOM", OP_ATOM),
    	std::pair<std::string, InstOpcode>("ATOMS", OP_ATOMS),
    	std::pair<std::string, InstOpcode>("ATOMG", OP_ATOMG),
    	std::pair<std::string, InstOpcode>("RED", OP_RED),
    	std::pair<std::string, InstOpcode>("CCTL", OP_CCTL),
    	std::pair<std::string, InstOpcode>("CCTLL", OP_CCTLL),
    	std::pair<std::string, InstOpcode>("ERRBAR", OP_ERRBAR),
    	std::pair<std::string, InstOpcode>("MEMBAR", OP_MEMBAR),
    	std::pair<std::string, InstOpcode>("CCTLT", OP_CCTLT),
    	std::pair<std::string, InstOpcode>("TEX", OP_TEX),
    	std::pair<std::string, InstOpcode>("TLD", OP_TLD),
    	std::pair<std::string, InstOpcode>("TLD4", OP_TLD4),
    	std::pair<std::string, InstOpcode>("TMML", OP_TMML),
    	std::pair<std::string, InstOpcode>("TXD", OP_TXD),
    	std::pair<std::string, InstOpcode>("TXQ", OP_TXQ),
    	std::pair<std::string, InstOpcode>("BMOV", OP_BMOV),
  		std::pair<std::string, InstOpcode>("BPT", OP_BPT),
    	std::pair<std::string, InstOpcode>("BRA", OP_BRA),
    	std::pair<std::string, InstOpcode>("BREAK", OP_BREAK),
    	std::pair<std::string, InstOpcode>("BRX", OP_BRX),
    	std::pair<std::string, InstOpcode>("BSSY", OP_BSSY),
    	std::pair<std::string, InstOpcode>("BSYNC", OP_BSYNC),
    	std::pair<std::string, InstOpcode>("CALL", OP_CALL),
    	std::pair<std::string, InstOpcode>("EXIT", OP_EXIT),
    	std::pair<std::string, InstOpcode>("JMP", OP_JMP),
    	std::pair<std::string, InstOpcode>("JMX", OP_JMX),
    	std::pair<std::string, InstOpcode>("KILL", OP_KILL),
    	std::pair<std::string, InstOpcode>("NANOSLEEP", OP_NANOSLEEP),
    	std::pair<std::string, InstOpcode>("RET", OP_RET),
    	std::pair<std::string, InstOpcode>("RPCMOV", OP_RPCMOV),
    	std::pair<std::string, InstOpcode>("RTT", OP_RTT),
    	std::pair<std::string, InstOpcode>("WARPSYNC", OP_WARPSYNC),
    	std::pair<std::string, InstOpcode>("YIELD", OP_YIELD),
    	std::pair<std::string, InstOpcode>("B2R", OP_B2R),
    	std::pair<std::string, InstOpcode>("BAR", OP_BAR),
    	std::pair<std::string, InstOpcode>("CS2R", OP_CS2R),
    	std::pair<std::string, InstOpcode>("CSMTEST", OP_CSMTEST),
    	std::pair<std::string, InstOpcode>("DEPBAR", OP_DEPBAR),
    	std::pair<std::string, InstOpcode>("GETLMEMBASE", OP_GETLMEMBASE),
    	std::pair<std::string, InstOpcode>("LEPC", OP_LEPC),
    	std::pair<std::string, InstOpcode>("NOP", OP_NOP),
    	std::pair<std::string, InstOpcode>("PMTRIG", OP_PMTRIG),
    	std::pair<std::string, InstOpcode>("R2B", OP_R2B),
    	std::pair<std::string, InstOpcode>("S2R", OP_S2R),
    	std::pair<std::string, InstOpcode>("SETCTAID", OP_SETCTAID),
    	std::pair<std::string, InstOpcode>("SETLMEMBASE", OP_SETLMEMBASE),
    	std::pair<std::string, InstOpcode>("VOTE", OP_VOTE),
    	std::pair<std::string, InstOpcode>("VOTE_VTG", OP_VOTE_VTG),
    	std::pair<std::string, InstOpcode>("BMMA", OP_BMMA),
    	std::pair<std::string, InstOpcode>("MOVM", OP_MOVM),
    	std::pair<std::string, InstOpcode>("LDSM", OP_LDSM),
    	std::pair<std::string, InstOpcode>("R2UR", OP_R2UR),
    	std::pair<std::string, InstOpcode>("S2UR", OP_S2UR),
    	std::pair<std::string, InstOpcode>("UBMSK", OP_UBMSK),
    	std::pair<std::string, InstOpcode>("UBREV", OP_UBREV),
    	std::pair<std::string, InstOpcode>("UCLEA", OP_UCLEA),
    	std::pair<std::string, InstOpcode>("UFLO", OP_UFLO),
    	std::pair<std::string, InstOpcode>("UIADD3", OP_UIADD3),
    	std::pair<std::string, InstOpcode>("UIMAD", OP_UIMAD),
    	std::pair<std::string, InstOpcode>("UISETP", OP_UISETP),
    	std::pair<std::string, InstOpcode>("ULDC", OP_ULDC),
    	std::pair<std::string, InstOpcode>("ULEA", OP_ULEA),
    	std::pair<std::string, InstOpcode>("ULOP", OP_ULOP),
    	std::pair<std::string, InstOpcode>("ULOP3", OP_ULOP3),
    	std::pair<std::string, InstOpcode>("ULOP32I", OP_ULOP32I),
    	std::pair<std::string, InstOpcode>("UMOV", OP_UMOV),
    	std::pair<std::string, InstOpcode>("UP2UR", OP_UP2UR),
    	std::pair<std::string, InstOpcode>("UPLOP3", OP_UPLOP3),
    	std::pair<std::string, InstOpcode>("UPOPC", OP_UPOPC),
    	std::pair<std::string, InstOpcode>("UPRMT", OP_UPRMT),
    	std::pair<std::string, InstOpcode>("UPSETP", OP_UPSETP),
    	std::pair<std::string, InstOpcode>("UR2UP", OP_UR2UP),
    	std::pair<std::string, InstOpcode>("USEL", OP_USEL),
    	std::pair<std::string, InstOpcode>("USGXT", OP_USGXT),
    	std::pair<std::string, InstOpcode>("USHF", OP_USHF),
    	std::pair<std::string, InstOpcode>("USHL", OP_USHL),
    	std::pair<std::string, InstOpcode>("USHR", OP_USHR),
    	std::pair<std::string, InstOpcode>("VOTEU", OP_VOTEU),
    	std::pair<std::string, InstOpcode>("SUATOM", OP_SUATOM),
    	std::pair<std::string, InstOpcode>("SULD", OP_SULD),
    	std::pair<std::string, InstOpcode>("SURED", OP_SURED),
    	std::pair<std::string, InstOpcode>("SUST", OP_SUST),
    	std::pair<std::string, InstOpcode>("BRXU", OP_BRXU),
    	std::pair<std::string, InstOpcode>("JMXU", OP_JMXU)
    };

    auto it = hashMap.find(str);
    if(it == hashMap.end()) {
        throw std::invalid_argument("[MapString2Opcode] Invalid input string.");
    }
    return it->second;
}
#endif
